import "dotenv/config";
import swaggerAutogen from "swagger-autogen";

const doc = {
  info: {
    title: "auth-api-express",
    description: "Documentation auto generated by swagger-autogen",
  },
  host: process.env.HOST_SWAGGER || "localhost:3000",
  schemes: ["http", "https"],
};

const outputFile = "./swagger-output.json";
const endpointsFiles = ["./server.js"];

swaggerAutogen()(outputFile, endpointsFiles, doc).then(() => {
  console.log("swagger-autogen: Documentation generated successfully");
});
